### ISSUE TITLE
Include Install Instructions

### ISSUE THREAD

**Issue by alin742** [MarthL/sts#10]
There are no install instructions in the README that could guide me through the setting up of the project.

I assume you need a database installed first probably SQL running on port 3306. Then first run the backend using the command

```sh
npm start
```
or 
```sh
npm nest start
```

Then you would run the frontend using the command

```sh
npm start
```

It would be really helpful if it was in the README.

**Comment by MarthL** [comment]
Hey Ali ! 

Indeed, we miss a full documentation to run the project. 

The main process to start the process is the following : 

- frontend : go within the directory and "npm run start" to start the client side
- backend: go to backend and run "npm run start:dev". start is also working but start:dev will save directly your changes and restart your backend in order to catch the error much easily. 

Nowadays, we are using wampp64 in order to get DB. TypeORM is a tool used inside NestJS who permits you to don't generate any SQL. Hence, you just have to create a database with a name similar in your environment. When it'll be done, the ORM will create automatically the schema. 

I will make a documentation today in order to be more clear about this part. I do appreciate your feedback !

**Comment by MarthL** [comment]
Issue is solved by @alin742 !
